micronaut:
    application:
        name: complete
    server:
        port: 9081
#tag::application[]
application:
    max: 50
#end::application[]
#tag::datasource[]
datasources:
    default:
        url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: ""
        driverClassName: org.h2.Driver
#end::datasource[]
#tag::jpa[]
jpa:
    default:
        packages-to-scan:
        - 'example.micronaut.domain' # <1>
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true
#end::jpa[]